<a href="https://colab.research.google.com/github/AndreaHernandez5072/HTML5-y-CSS3/blob/main/Laboratorio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Laboratorio 1 - Python**

In [13]:
import numpy as np #Permite cálculo númerio, análisis de datos y gestión de array
import timeit #libreria para tomar tiempo
import pandas as pd
import matplotlib.pyplot as plt

Operaciones vectorizadas estas son las operaciones vectorizadas
Todo ejecuta de manera secuencial, si dejo el proyecto por 20 minutos, debo ejecutar todo. Ir a ventana denominada entorno de ejecución y elegir la opción "Ejecutar todo".

Preferencia usar una operación vectorizada en lugar de hacer ciclos.

In [14]:
total = 0

#for desde 0 hasta 15 mil
for item in range(0,15000):
  total += item
a = total
print ("\n Total fue: "+str(a))
print ("Tiempo que tomo la suma iterativa;",end="")
%timeit a #Tiempo de ejecución


 Total fue: 112492500
Tiempo que tomo la suma iterativa;31.7 ns ± 0.68 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [28]:
d = np.arange(15000) #crear un vector entre 0 y 15 mil
d
print("\nResultado de la suma del conetnido array es ",np.sum(d))
print("El tiempo que toma efectuar la operación vectorizada es ", end="")
%timeit np.sum(d)


Resultado de la suma del conetnido array es  112492500
El tiempo que toma efectuar la operación vectorizada es 7.5 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# **Más operaciones vectorizadas**
Al usar float, debemos tener cuidado debido a que python almacena todos los decimales y si hacemos un if debemos considerar eso.

Es un lenguaje interpretado, cargo a memoria en conformidad de como ejecute. Entonces, declaro una variable en la parte superior que ya habia declarado abajo, tendra el valor de abajo en lugar de arriba porque primero ejecute el valor de abajo.

In [36]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(2.3,1,3)],dtype=float) #
b

array([[1.5, 2. , 3. ],
       [2.3, 1. , 3. ]])

El lenguaje sigue las reglas del algebra lineal. Es decir, puede hacer suma de producto cruz y producto punto. Se puede observar en el siguiente bloque de código.

In [38]:
c = a+b
c

array([[2.5, 4. , 6. ],
       [3.3, 3. , 6. ]])

Puede hacer operaciones vectoriales sin ciclos. Asimismo, puede hacer con booleanos y otros valores

In [39]:
h=a/b
h

array([[0.66666667, 1.        , 1.        ],
       [0.43478261, 2.        , 1.        ]])

Puedo hacer operaciones booleanas vectorizadas, permitiendo hacer cualquier tipo de operación. Sin importar el dato.

In [40]:
a == b

array([[False,  True,  True],
       [False, False,  True]])

In [44]:
a < b

array([[ True, False, False],
       [ True, False, False]])

Python, utiliza listas pero no es tan necesario

# Funciones estadísticas
La única función que no tiene es la moda

In [48]:
a.sum()
a.min()
a.max()
a.mean() #media
np.median(a) #mediana
np.std(a)#desviación estandar

0.816496580927726

# IF THEN ELSE
Cimentación es muy importante, es decir debo estar un tap para que entienda que está adentro del if.

Aquí no existe un begin y end

In [52]:
edad_alumno= 15
edad_minima_votacion=18

if edad_alumno >= edad_minima_votacion:
  #Adentro del IF
  print("El alumno puede votar")
else:
  #Adentro del else
  print("El alumno no puede votar")
  print("\nEsto es parte del ELSE")

#Afuera del ELSE
print("\nAfuera del ELSE")


El alumno no puede votar

Esto es parte del ELSE

Afuera del ELSE


In [54]:
monto = 1000.00
pais ="HN"
interes = 0.0

if pais=="GT":
  interes=0.1
elif pais =="HN":
  interes=0.2
else:
  interes=0.6

interes

0.2

In [55]:
x=10
f= 2*x+1 #f(x)
g= 5*x+7 #g(x)

In [57]:
if x>=0:
  y=f
else:
  y=g

y

21

In [58]:
y = f if x >= 0 else g
y

21

Definición de un procedimiento

In [66]:
def predecir(modelo=1,x=0):
  y=0 #siempre hay que poner un valor por default por que no inicializamos
  if modelo == 1:
    y = x*2
  elif modelo ==2:
    y = x**2 + 1
  elif modelo ==3:
    y = x/2 +5
  else:
    y = x

  return y

  print(predecir(2,3))